module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Answers",
      [
        {
          title: "rjkz",
          id_card: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "rjkz",
          id_card: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Answers", null, {});
  },
};
